services:
  - type: web
    name: face-attendance
    env: python
    plan: free
    region: singapore
    buildCommand: |
      python -m pip install --upgrade pip
      pip install setuptools==69.5.1
      pip install wheel==0.43.0
      pip install cmake==3.28.3
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9